name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 15
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 15
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build with Gradle + checkstyle PMD + CPD + spotbugs + tests + test coverage report
      run: ./gradlew build